"""HTML report generator for news summaries."""

import html
import os
from collections import OrderedDict


def group_by_topic(items: list[dict]) -> OrderedDict:
    """Group items by topic, preserving insertion order."""
    grouped = OrderedDict()
    for item in items:
        topic = item.get('topic', 'Other')
        if topic not in grouped:
            grouped[topic] = []
        grouped[topic].append(item)
    return grouped


def generate_html(items: list[dict], date_str: str) -> str:
    """Generate HTML report from summarized items."""
    grouped = group_by_topic(items)

    sections_html = ''
    toc_items = ''

    for topic, topic_items in grouped.items():
        anchor = topic.replace('/', '-').replace(' ', '-')
        toc_items += f'<li><a href="#{anchor}">{html.escape(topic)}</a> ({len(topic_items)})</li>\n'

        items_html = ''
        for item in topic_items:
            title = item.get('title', '') or item.get('summary', '')[:80] or 'No Title'
            title_escaped = html.escape(title)
            link = html.escape(item.get('link', '#'))
            feed = html.escape(item.get('feed', ''))
            time_str = html.escape(item.get('time', ''))
            summary = html.escape(item.get('summary', ''))

            items_html += f'''
        <article class="news-item">
          <h3><a href="{link}" target="_blank" rel="noopener">{title_escaped}</a></h3>
          <div class="meta">
            <span class="feed">来源: {feed}</span>
            <span class="time">{time_str}</span>
          </div>
          <p class="summary">{summary}</p>
        </article>
'''

        sections_html += f'''
    <section id="{anchor}" class="topic-section">
      <h2>{html.escape(topic)} <span class="count">({len(topic_items)}条)</span></h2>
      {items_html}
    </section>
'''

    toc_html = ''
    if toc_items:
        toc_html = f'''
    <nav class="toc">
      <h2>目录</h2>
      <ul>
        {toc_items}
      </ul>
    </nav>
'''

    no_items_msg = ''
    if not items:
        no_items_msg = '<p class="empty">No news items for this report.</p>'

    return f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Report - {html.escape(date_str)}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }}
    header {{ border-bottom: 2px solid #007acc; margin-bottom: 24px; padding-bottom: 12px; }}
    header h1 {{ color: #007acc; margin: 0; }}
    header .date {{ color: #666; font-size: 0.9em; }}
    .toc {{ background: #f5f7fa; border-radius: 8px; padding: 16px 20px; margin-bottom: 24px; }}
    .toc h2 {{ margin-top: 0; font-size: 1.1em; color: #555; }}
    .toc ul {{ list-style: none; padding-left: 0; }}
    .toc li {{ margin: 4px 0; }}
    .toc a {{ color: #007acc; text-decoration: none; }}
    .toc a:hover {{ text-decoration: underline; }}
    .topic-section {{ margin-bottom: 32px; }}
    .topic-section h2 {{ color: #007acc; border-bottom: 1px solid #e0e0e0; padding-bottom: 6px; }}
    .count {{ font-weight: normal; color: #888; font-size: 0.8em; }}
    .news-item {{ background: #fafafa; border-left: 3px solid #007acc; padding: 12px 16px; margin-bottom: 12px; border-radius: 0 6px 6px 0; }}
    .news-item h3 {{ margin: 0 0 6px 0; font-size: 1.05em; }}
    .news-item h3 a {{ color: #333; text-decoration: none; }}
    .news-item h3 a:hover {{ color: #007acc; }}
    .meta {{ font-size: 0.8em; color: #888; margin-bottom: 8px; }}
    .meta span {{ margin-right: 12px; }}
    .summary {{ margin: 0; color: #444; }}
    .empty {{ text-align: center; color: #888; padding: 40px; }}
    footer {{ text-align: center; color: #aaa; font-size: 0.8em; margin-top: 40px; border-top: 1px solid #e0e0e0; padding-top: 16px; }}
  </style>
</head>
<body>
  <header>
    <h1>Daily Report</h1>
    <div class="date">{html.escape(date_str)}</div>
  </header>
  {toc_html}
  {no_items_msg}
  {sections_html}
  <footer>
    <p>Generated by Daily Report System</p>
  </footer>
</body>
</html>
'''


def save_report(html_content: str, date_str: str, archive_dir: str) -> str:
    """Save HTML report to archive_dir/<date_str>.html. Returns file path."""
    os.makedirs(archive_dir, exist_ok=True)
    filepath = os.path.join(archive_dir, f'{date_str}.html')
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(html_content)
    return filepath
